name: Test Porta 22 su ltocav911

on:
  workflow_dispatch: 

jobs:
  check-port:
    runs-on: ubuntu-latest # Runner cloud di GitHub

    steps:
    - name: Verifica connettività sulla porta 22
      run: |
        echo "Verifica accesso porta 22 su ltocav911"
        
        
        if nc -zv -w 5 ${{ secrets.SSH_HOST }} 22; then
          echo "======================================================"
          echo "🟢 SUCCESSO: La porta 22 su ltocav911 è APERTA verso GitHub!"
          echo "======================================================"
        else
          echo "======================================================"
          echo "🔴 ERRORE: La porta 22 è CHIUSA verso GitHub."
          echo "======================================================"
          exit 1
        fi
