name: Test Connettivita Porta 22

on: [push]

jobs:
  check-port:
    runs-on: ubuntu-latest

    steps:
    - name: Tentativo di connessione alla porta 22
      run: |
        echo "Tentativo di connessione..."
        if nc -z -w 10 ltocav911.admin.servizi.rai.it 22; then
          echo "✅ SUCCESSO: La porta 22 è APERTA!"
        else
          echo "❌ ERRORE: La porta 22 è CHIUSA o bloccata."
          exit 1
        fi
